name: Prepare Tauri Build Config
description: Render temporary Tauri build config with updater settings

inputs:
  updater-endpoint:
    description: Updater latest.json endpoint URL override
    required: false
    default: ""
  updater-pubkey:
    description: Updater public key override
    required: false
    default: ""
  output-path:
    description: Generated Tauri build config path
    required: false
    default: src-tauri/tauri.build.config.json

runs:
  using: composite
  steps:
    - name: Render config
      shell: bash
      run: |
        set -euo pipefail
        python_cmd="python3"
        if ! command -v "${python_cmd}" >/dev/null 2>&1; then
          python_cmd="python"
        fi
        if ! command -v "${python_cmd}" >/dev/null 2>&1; then
          echo "::error::Python interpreter not found (expected python3 or python)." >&2
          exit 1
        fi
        "${python_cmd}" scripts/ci/render-tauri-build-config.py \
          --output "${{ inputs.output-path }}" \
          --updater-endpoint "${{ inputs.updater-endpoint }}" \
          --updater-pubkey "${{ inputs.updater-pubkey }}"
        echo "ASTRBOT_TAURI_CONFIG_PATH=${{ inputs.output-path }}" >> "${GITHUB_ENV}"
